CREATE TYPE car_groups AS ENUM ('CLASSIC', 'NOT_CLASSIC');

CREATE TABLE IF NOT EXISTS cars
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    model  varchar(255)                                       NOT NULL,
    groups car_groups                                         NOT NULL
);

